version: '3.9'

services:

  api-get-linguagens-program:
    container_name: api-get-linguagens-program
    image: api-get-linguagens-program
    restart: always
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    networks:
      - backend
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      - backend
    environment:
      - MONGO_INITDB_DATABASE=linguagens-db
      - MONGO_INITDB_ROOT_USERNAME=linguagens
      - MONGO_INITDB_ROOT_PASSWORD=program

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=linguagens
      - ME_CONFIG_MONGODB_ADMINPASSWORD=program
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=program
    depends_on:
      - mongo
    networks:
      - backend

  sonarqube:
    image: sonarqube
    hostname: sonarqube
    container_name: sonarqube
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"
    networks:
      - backend

networks:
    backend:
        driver: bridge

volumes:
    sonarqube_data:
    sonarqube_extensions:
    sonarqube_logs:
